### ISSUE TITLE
No image in ListItem.Art(videothumb)

### ISSUE THREAD

**Issue by manfeed** [the-black-eagle/script.videolinks#2]
With the new feature already merged in Omega I'm unable to get any image from ListItem.Art(videothumb). The video links do get added faultlessly. Thanks!

**Comment by the-black-eagle** [comment]
Thanks for the report.  Seems to be working here OK, but I will take a look with a fresh build to see if there is anything I can spot.

<a href="https://ibb.co/99tDqpg"><img src="https://i.ibb.co/99tDqpg/screenshot00113.png" alt="screenshot00113" border="0"></a>
Album cover

<a href="https://ibb.co/mDBrLmz"><img src="https://i.ibb.co/mDBrLmz/screenshot00112.png" alt="screenshot00112" border="0"></a>
Videothumb

**Comment by the-black-eagle** [comment]
@manfeed  Found some time to look at this and did indeed find an error which is fixed in the latest release :)
